#!/usr/bin/env bash

source ./common.sh

if [ $ACL_MODE == "DENY_SOME_ALLOW_ALL" ]; then
  for IP in ${IPS[@]}; do
    iptables -D $IPTABLES_DOCKER_CHAIN -i $DOCKER_CONTAINER_INTERFACE -s $IP -j DROP
    iptables -D $IPTABLES_DOCKER_CHAIN -o $DOCKER_CONTAINER_INTERFACE -d $IP -j DROP
  done
  iptables -D $IPTABLES_DOCKER_CHAIN -i $DOCKER_CONTAINER_INTERFACE -j ACCEPT
  iptables -D $IPTABLES_DOCKER_CHAIN -o $DOCKER_CONTAINER_INTERFACE -j ACCEPT
elif [ $ACL_MODE == "ALLOW_SOME_DENY_ALL" ]; then
  for IP in ${IPS[@]}; do
    iptables -D $IPTABLES_DOCKER_CHAIN -i $DOCKER_CONTAINER_INTERFACE -s $IP -j ACCEPT
    iptables -D $IPTABLES_DOCKER_CHAIN -o $DOCKER_CONTAINER_INTERFACE -d $IP -j ACCEPT
  done
  iptables -D $IPTABLES_DOCKER_CHAIN -i $DOCKER_CONTAINER_INTERFACE -j DROP
  iptables -D $IPTABLES_DOCKER_CHAIN -o $DOCKER_CONTAINER_INTERFACE -j DROP
else
  echo "NOT ALLOWED ACL_MODE ${ACL_MODE}"
  exit 1
fi

# allow dns
iptables -D $IPTABLES_DOCKER_CHAIN -o $DOCKER_CONTAINER_INTERFACE -d $WG_DEFAULT_DNS -j ACCEPT
iptables -D $IPTABLES_DOCKER_CHAIN -i $DOCKER_CONTAINER_INTERFACE -s $WG_DEFAULT_DNS -j ACCEPT
