services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=${WG_EASY_HOST:-192.168.1.103}
      - PORT=9001
      - WG_PORT=51820
      - PASSWORD=${WG_EASY_PASSWORD:-root}
      - WG_POST_UP=/etc/wireguard/postup.sh
      - WG_POST_DOWN=/etc/wireguard/postdown.sh
    restart: unless-stopped
    volumes:
      - ./wireguard:/etc/wireguard
    networks:
      wg:
        ipv4_address: 192.168.1.103
    ports:
      - 51820:51820/udp
      - 9001:9001/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

networks:
  wg:
    name: wg-easy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
