services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./wireguard:/etc/wireguard
    networks:
      wg:
        ipv4_address: ${WG_CONTAINER_IP}
    ports:
      - ${WG_PORT}:${WG_PORT}/udp
      - ${PORT}:${PORT}/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

networks:
  wg:
    name: ${WG_CONTAINER_NETWORK_NAME}
    driver: bridge
    ipam:
      config:
        - subnet: ${WG_CONTAINER_SUBNET}
          gateway: ${WG_CONTAINER_GATEWAY}
